var yo=require('yo-yo');

module.exports=function(){
return (function () {
      
      var ac = require('c:\\xampp\\htdocs\\juridico\\node_modules\\yo-yoify\\lib\\appendChild.js')
      var bel10 = document.createElement("form")
bel10.setAttribute("method", "POST")
bel10.setAttribute("id", "SubDocumentos")
bel10.setAttribute("class", "form-inline")
var bel2 = document.createElement("div")
bel2.setAttribute("class", "form-group idDocumento")
var bel0 = document.createElement("label")
bel0.setAttribute("htmlFor", "idDocumento")
ac(bel0, ["Tipo de Documento"])
var bel1 = document.createElement("select")
bel1.setAttribute("name", "idDocumento")
bel1.setAttribute("id", "idDocumento")
bel1.setAttribute("required", "required")
bel1.setAttribute("class", "form-control")
ac(bel1, ["\n    "])
ac(bel2, ["\n    ",bel0,"\n    ",bel1,"\n"])
var bel6 = document.createElement("div")
bel6.setAttribute("class", "form-group nombre")
var bel4 = document.createElement("label")
bel4.setAttribute("htmlFor", "nombre")
var bel3 = document.createElement("strong")
ac(bel3, ["(Nombre  Apellido Paterno  Apellido Materno)"])
ac(bel4, ["Nombre ",bel3])
var bel5 = document.createElement("input")
bel5.setAttribute("type", "text")
bel5.setAttribute("id", "nombre")
bel5.setAttribute("placeholder", "Nombre")
bel5.setAttribute("required", "required")
bel5.setAttribute("pattern", "[A-Za-z].{10,49}")
bel5.setAttribute("name", "nombre")
bel5.setAttribute("title", "Nombre Incorrecto o Caracteres maximos")
bel5.setAttribute("class", "form-control")
ac(bel6, ["\n    ",bel4,"\n    ",bel5,"\n"])
var bel9 = document.createElement("div")
bel9.setAttribute("class", "form-group send")
var bel7 = document.createElement("input")
bel7.setAttribute("type", "submit")
bel7.setAttribute("value", "Guardar")
bel7.setAttribute("class", "btn btn-primary btn-sm")
var bel8 = document.createElement("button")
bel8.setAttribute("id", "cancelar")
bel8.setAttribute("class", "btn btn-default btn-sm")
ac(bel8, ["Cancelar"])
ac(bel9, ["\n    ",bel7,"\n    ",bel8,"\n"])
ac(bel10, ["\n   ",bel2,"\n",bel6,"\n",bel9,"\n"])
      return bel10
    }());

}