var yo=require('yo-yo');

module.exports=function(){
return (function () {
      
      var ac = require('c:\\xampp\\htdocs\\juridico\\node_modules\\yo-yoify\\lib\\appendChild.js')
      var bel72 = document.createElement("form")
bel72.setAttribute("method", "POST")
bel72.setAttribute("id", "UpdateVolantes")
bel72.setAttribute("class", "form-inline")
var bel15 = document.createElement("div")
bel15.setAttribute("class", "headerVolante")
var bel2 = document.createElement("div")
bel2.setAttribute("class", "form-group idDocumento")
var bel0 = document.createElement("label")
bel0.setAttribute("htmlFor", "idDocumento")
ac(bel0, ["Tipo de Documento"])
var bel1 = document.createElement("select")
bel1.setAttribute("name", "idDocumento")
bel1.setAttribute("id", "idDocumento")
bel1.setAttribute("required", "required")
bel1.setAttribute("class", "form-control")
ac(bel1, ["\n    "])
ac(bel2, ["\n    ",bel0,"\n    ",bel1,"\n"])
var bel5 = document.createElement("div")
bel5.setAttribute("class", "form-group subDocumento")
var bel3 = document.createElement("label")
bel3.setAttribute("htmlFor", "subDocumento")
ac(bel3, ["Tipo de SubDocumento"])
var bel4 = document.createElement("select")
bel4.setAttribute("name", "idSubTipoDocumento")
bel4.setAttribute("id", "subDocumento")
bel4.setAttribute("required", "required")
bel4.setAttribute("class", "form-control")
ac(bel4, ["\n    "])
ac(bel5, ["\n    ",bel3,"\n    ",bel4,"\n"])
var bel11 = document.createElement("div")
bel11.setAttribute("class", "form-group Promocion")
var bel6 = document.createElement("label")
bel6.setAttribute("htmlFor", "subDocumento")
ac(bel6, ["Promocion de Accion"])
var bel10 = document.createElement("select")
bel10.setAttribute("name", "promocion")
bel10.setAttribute("id", "promocion")
bel10.setAttribute("required", "required")
bel10.setAttribute("class", "form-control")
var bel7 = document.createElement("option")
bel7.setAttribute("value", "NO")
ac(bel7, [" Escoga Opcion "])
var bel8 = document.createElement("option")
bel8.setAttribute("value", "SI")
ac(bel8, [" SI "])
var bel9 = document.createElement("option")
bel9.setAttribute("value", "NO")
ac(bel9, [" NO "])
ac(bel10, ["\n        ",bel7,"\n        ",bel8,"\n        ",bel9,"\n    "])
ac(bel11, ["\n    ",bel6,"\n    ",bel10,"\n"])
var bel14 = document.createElement("div")
bel14.setAttribute("class", "form-group cveAuditoria")
var bel12 = document.createElement("label")
bel12.setAttribute("htmlFor", "cveAuditoria")
ac(bel12, ["Clave de Auditoria"])
var bel13 = document.createElement("select")
bel13.setAttribute("name", "cveAuditoria")
bel13.setAttribute("id", "cveAuditoria")
bel13.setAttribute("required", "required")
bel13.setAttribute("class", "form-control")
ac(bel13, ["\n    "])
ac(bel14, ["\n    ",bel12,"\n    ",bel13,"\n"])
ac(bel15, ["\n",bel2,"\n\n",bel5,"\n\n",bel11,"\n\n\n\n",bel14,"\n\n"])
var bel22 = document.createElement("div")
bel22.setAttribute("class", "datosAuditoria")
var bel18 = document.createElement("div")
bel18.setAttribute("class", "form-group idUnidad")
var bel16 = document.createElement("label")
bel16.setAttribute("htmlFor", "idUnidad")
ac(bel16, ["Sujeto de Fiscalizacion"])
var bel17 = document.createElement("input")
bel17.setAttribute("type", "text")
bel17.setAttribute("id", "idUnidad")
bel17.setAttribute("disabled", "true")
bel17.setAttribute("class", "form-control")
ac(bel18, ["\n    ",bel16,"\n    ",bel17,"\n"])
var bel21 = document.createElement("div")
bel21.setAttribute("class", "form-group idObjeto")
var bel19 = document.createElement("label")
bel19.setAttribute("htmlFor", "idObjeto")
ac(bel19, ["Rubro"])
var bel20 = document.createElement("input")
bel20.setAttribute("type", "text")
bel20.setAttribute("id", "idObjeto")
bel20.setAttribute("disabled", "true")
bel20.setAttribute("class", "form-control")
ac(bel21, ["\n    ",bel19,"\n    ",bel20,"\n"])
ac(bel22, ["\n\n",bel18,"\n\n",bel21,"\n\n"])
var bel71 = document.createElement("div")
bel71.setAttribute("class", "contentVolante")
var bel25 = document.createElement("div")
bel25.setAttribute("class", "form-group Folio")
var bel23 = document.createElement("label")
bel23.setAttribute("htmlFor", "Folio")
ac(bel23, ["Folio"])
var bel24 = document.createElement("input")
bel24.setAttribute("type", "number")
bel24.setAttribute("id", "Folio")
bel24.setAttribute("name", "folio")
bel24.setAttribute("required", "required")
bel24.setAttribute("class", "form-control")
ac(bel25, ["\n    ",bel23,"\n    ",bel24,"\n"])
var bel28 = document.createElement("div")
bel28.setAttribute("class", "form-group numDocumento")
var bel26 = document.createElement("label")
bel26.setAttribute("htmlFor", "numDocumento")
ac(bel26, ["Numero de Documento"])
var bel27 = document.createElement("input")
bel27.setAttribute("type", "text")
bel27.setAttribute("id", "numDocumento")
bel27.setAttribute("name", "numDocumento")
bel27.setAttribute("required", "required")
bel27.setAttribute("class", "form-control")
ac(bel28, ["\n    ",bel26,"\n    ",bel27,"\n"])
var bel31 = document.createElement("div")
bel31.setAttribute("class", "form-group fDocumento")
var bel29 = document.createElement("label")
bel29.setAttribute("htmlFor", "fDocumento")
ac(bel29, ["Fecha de Documento"])
var bel30 = document.createElement("input")
bel30.setAttribute("type", "text")
bel30.setAttribute("id", "fDocumento")
bel30.setAttribute("name", "fDocumento")
bel30.setAttribute("required", "required")
bel30.setAttribute("pattern", "(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))")
bel30.setAttribute("class", "form-control")
ac(bel31, ["\n    ",bel29,"\n    ",bel30,"\n"])
var bel34 = document.createElement("div")
bel34.setAttribute("class", "form-group anexos")
var bel32 = document.createElement("label")
bel32.setAttribute("htmlFor", "anexos")
ac(bel32, ["Numero de Anexos"])
var bel33 = document.createElement("input")
bel33.setAttribute("type", "number")
bel33.setAttribute("id", "anexos")
bel33.setAttribute("name", "anexos")
bel33.setAttribute("required", "required")
bel33.setAttribute("class", "form-control")
ac(bel34, ["\n    ",bel32,"\n    ",bel33,"\n"])
var bel37 = document.createElement("div")
bel37.setAttribute("class", "form-group fRecepcion")
var bel35 = document.createElement("label")
bel35.setAttribute("htmlFor", "fRecepcion")
ac(bel35, ["Fecha de Recepcion"])
var bel36 = document.createElement("input")
bel36.setAttribute("type", "text")
bel36.setAttribute("id", "fRecepcion")
bel36.setAttribute("name", "fRecepcion")
bel36.setAttribute("required", "required")
bel36.setAttribute("pattern", "(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))")
bel36.setAttribute("class", "form-control")
ac(bel37, ["\n    ",bel35,"\n    ",bel36,"\n"])
var bel40 = document.createElement("div")
bel40.setAttribute("class", "form-group hRecepcion")
var bel38 = document.createElement("label")
bel38.setAttribute("htmlFor", "hRecepcion")
ac(bel38, ["Hora de Recepcion"])
var bel39 = document.createElement("input")
bel39.setAttribute("type", "time")
bel39.setAttribute("id", "hRecepcion")
bel39.setAttribute("name", "hRecepcion")
bel39.setAttribute("required", "required")
bel39.setAttribute("class", "form-control")
ac(bel40, ["\n    ",bel38,"\n    ",bel39,"\n"])
var bel43 = document.createElement("div")
bel43.setAttribute("class", "form-group idRemitente")
var bel41 = document.createElement("label")
bel41.setAttribute("htmlFor", "idRemitente")
ac(bel41, ["Remitente"])
var bel42 = document.createElement("select")
bel42.setAttribute("name", "idRemitente")
bel42.setAttribute("id", "idRemitente")
bel42.setAttribute("required", "required")
bel42.setAttribute("class", "form-control")
ac(bel42, ["\n    "])
ac(bel43, ["\n    ",bel41,"\n    ",bel42,"\n"])
var bel46 = document.createElement("div")
bel46.setAttribute("class", "form-group NombreRemitente")
var bel44 = document.createElement("label")
bel44.setAttribute("htmlFor", "NombreRemitente")
ac(bel44, ["Nombre"])
var bel45 = document.createElement("input")
bel45.setAttribute("type", "text")
bel45.setAttribute("id", "NombreRemitente")
bel45.setAttribute("disabled", "true")
bel45.setAttribute("class", "form-control")
ac(bel46, ["\n    ",bel44,"\n    ",bel45,"\n"])
var bel49 = document.createElement("div")
bel49.setAttribute("class", "form-group cargo")
var bel47 = document.createElement("label")
bel47.setAttribute("htmlFor", "cargo")
ac(bel47, ["Cargo"])
var bel48 = document.createElement("input")
bel48.setAttribute("type", "text")
bel48.setAttribute("id", "cargo")
bel48.setAttribute("disabled", "true")
bel48.setAttribute("class", "form-control")
ac(bel49, ["\n    ",bel47,"\n    ",bel48,"\n"])
var bel52 = document.createElement("div")
bel52.setAttribute("class", "form-group dependencia")
var bel50 = document.createElement("label")
bel50.setAttribute("htmlFor", "dependencia")
ac(bel50, ["Dependencia"])
var bel51 = document.createElement("input")
bel51.setAttribute("type", "text")
bel51.setAttribute("id", "dependencia")
bel51.setAttribute("disabled", "true")
bel51.setAttribute("class", "form-control")
ac(bel52, ["\n    ",bel50,"\n    ",bel51,"\n"])
var bel55 = document.createElement("div")
bel55.setAttribute("class", "form-group Destinatario")
var bel53 = document.createElement("label")
bel53.setAttribute("htmlFor", "Destinatario")
ac(bel53, ["Destinatario"])
var bel54 = document.createElement("input")
bel54.setAttribute("type", "text")
bel54.setAttribute("id", "Destinatario")
bel54.setAttribute("name", "destinatario")
bel54.setAttribute("placeholder", "Destinatario")
bel54.setAttribute("class", "form-control")
ac(bel55, ["\n    ",bel53,"\n    ",bel54,"\n"])
var bel58 = document.createElement("div")
bel58.setAttribute("class", "form-group Asunto")
var bel56 = document.createElement("label")
bel56.setAttribute("htmlFor", "Asunto")
ac(bel56, ["Asunto"])
var bel57 = document.createElement("textarea")
bel57.setAttribute("rows", "3")
bel57.setAttribute("name", "asunto")
bel57.setAttribute("required", "required")
bel57.setAttribute("placeholder", "Asunto")
bel57.setAttribute("class", "form-control")
ac(bel58, ["\n    ",bel56,"\n    ",bel57,"\n"])
var bel61 = document.createElement("div")
bel61.setAttribute("class", "form-group idCaracter")
var bel59 = document.createElement("label")
bel59.setAttribute("htmlFor", "idCaracter")
ac(bel59, ["Caracter"])
var bel60 = document.createElement("select")
bel60.setAttribute("name", "idCaracter")
bel60.setAttribute("id", "idCaracter")
bel60.setAttribute("required", "required")
bel60.setAttribute("class", "form-control")
ac(bel60, ["\n    "])
ac(bel61, ["\n    ",bel59,"\n    ",bel60,"\n"])
var bel64 = document.createElement("div")
bel64.setAttribute("class", "form-group idTurnado")
var bel62 = document.createElement("label")
bel62.setAttribute("htmlFor", "idTurnado")
ac(bel62, ["Turnado a:"])
var bel63 = document.createElement("select")
bel63.setAttribute("name", "idTurnado")
bel63.setAttribute("id", "idTurnado")
bel63.setAttribute("required", "required")
bel63.setAttribute("class", "form-control")
ac(bel63, ["\n    "])
ac(bel64, ["\n    ",bel62,"\n    ",bel63,"\n"])
var bel67 = document.createElement("div")
bel67.setAttribute("class", "form-group idAccion")
var bel65 = document.createElement("label")
bel65.setAttribute("htmlFor", "idAccion")
ac(bel65, ["Instruccion"])
var bel66 = document.createElement("select")
bel66.setAttribute("name", "idAccion")
bel66.setAttribute("id", "idAccion")
bel66.setAttribute("required", "required")
bel66.setAttribute("class", "form-control")
ac(bel66, ["\n    "])
ac(bel67, ["\n    ",bel65,"\n    ",bel66,"\n"])
var bel70 = document.createElement("div")
bel70.setAttribute("class", "form-group send")
var bel68 = document.createElement("input")
bel68.setAttribute("type", "submit")
bel68.setAttribute("value", "Guardar")
bel68.setAttribute("class", "btn btn-primary btn-sm")
var bel69 = document.createElement("button")
bel69.setAttribute("id", "cancelar")
bel69.setAttribute("class", "btn btn-default btn-sm")
ac(bel69, ["Cancelar"])
ac(bel70, ["\n    ",bel68,"\n    ",bel69,"\n"])
ac(bel71, ["\n\n",bel25,"\n\n\n",bel28,"\n\n",bel31,"\n\n",bel34,"\n\n",bel37,"\n\n",bel40,"\n\n\n",bel43,"\n\n",bel46,"\n\n\n",bel49,"\n\n",bel52,"\n\n",bel55,"\n\n",bel58,"\n\n",bel61,"\n\n",bel64,"\n\n",bel67,"\n\n\n\n\n\n\n\n\n\n\n\n",bel70,"\n\n\n"])
ac(bel72, ["\n",bel15,"\n\n",bel22,"\n\n\n\n",bel71,"\n"])
      return bel72
    }());

}