var yo=require('yo-yo');

module.exports=function(){
return (function () {
      
      var ac = require('c:\\xampp\\htdocs\\juridico\\node_modules\\yo-yoify\\lib\\appendChild.js')
      var bel33 = document.createElement("form")
bel33.setAttribute("method", "POST")
bel33.setAttribute("id", "Volantes")
bel33.setAttribute("class", "form-inline")
var bel2 = document.createElement("div")
bel2.setAttribute("class", "form-group idDocumento")
var bel0 = document.createElement("label")
bel0.setAttribute("htmlFor", "idDocumento")
ac(bel0, ["Tipo de Documento"])
var bel1 = document.createElement("select")
bel1.setAttribute("name", "idDocumento")
bel1.setAttribute("id", "idDocumento")
bel1.setAttribute("required", "required")
bel1.setAttribute("class", "form-control")
ac(bel1, ["\n    "])
ac(bel2, ["\n    ",bel0,"\n    ",bel1,"\n"])
var bel5 = document.createElement("div")
bel5.setAttribute("class", "form-group subDocumento")
var bel3 = document.createElement("label")
bel3.setAttribute("htmlFor", "subDocumento")
ac(bel3, ["Tipo de SubDocumento"])
var bel4 = document.createElement("select")
bel4.setAttribute("name", "subDocumento")
bel4.setAttribute("id", "subDocumento")
bel4.setAttribute("required", "required")
bel4.setAttribute("class", "form-control")
ac(bel4, ["\n    "])
ac(bel5, ["\n    ",bel3,"\n    ",bel4,"\n"])
var bel11 = document.createElement("div")
bel11.setAttribute("class", "form-group Promocion")
var bel6 = document.createElement("label")
bel6.setAttribute("htmlFor", "subDocumento")
ac(bel6, ["Promocion de Accion"])
var bel10 = document.createElement("select")
bel10.setAttribute("name", "promocion")
bel10.setAttribute("id", "promocion")
bel10.setAttribute("required", "required")
bel10.setAttribute("class", "form-control")
var bel7 = document.createElement("option")
bel7.setAttribute("val", "0")
ac(bel7, [" Escoga Opcion "])
var bel8 = document.createElement("option")
bel8.setAttribute("val", "SI")
ac(bel8, [" SI "])
var bel9 = document.createElement("option")
bel9.setAttribute("val", "NO")
ac(bel9, [" NO "])
ac(bel10, ["\n        ",bel7,"\n        ",bel8,"\n        ",bel9,"\n    "])
ac(bel11, ["\n    ",bel6,"\n    ",bel10,"\n"])
var bel14 = document.createElement("div")
bel14.setAttribute("class", "form-group Folio")
var bel12 = document.createElement("label")
bel12.setAttribute("htmlFor", "Folio")
ac(bel12, ["Numero de Folio"])
var bel13 = document.createElement("input")
bel13.setAttribute("type", "number")
bel13.setAttribute("id", "Folio")
bel13.setAttribute("name", "Folio")
bel13.setAttribute("required", "required")
bel13.setAttribute("class", "form-control")
ac(bel14, ["\n    ",bel12,"\n    ",bel13,"\n"])
var bel17 = document.createElement("div")
bel17.setAttribute("class", "form-group numDocumento")
var bel15 = document.createElement("label")
bel15.setAttribute("htmlFor", "numDocumento")
ac(bel15, ["Numero de Documento"])
var bel16 = document.createElement("input")
bel16.setAttribute("type", "text")
bel16.setAttribute("id", "numDocumento")
bel16.setAttribute("name", "numDocumento")
bel16.setAttribute("required", "required")
bel16.setAttribute("class", "form-control")
ac(bel17, ["\n    ",bel15,"\n    ",bel16,"\n"])
var bel20 = document.createElement("div")
bel20.setAttribute("class", "form-group fDocumento")
var bel18 = document.createElement("label")
bel18.setAttribute("htmlFor", "fDocumento")
ac(bel18, ["Fecha de Documento"])
var bel19 = document.createElement("input")
bel19.setAttribute("type", "text")
bel19.setAttribute("id", "datepicker")
bel19.setAttribute("name", "fDocumento")
bel19.setAttribute("required", "required")
bel19.setAttribute("class", "form-control")
ac(bel20, ["\n    ",bel18,"\n    ",bel19,"\n"])
var bel23 = document.createElement("div")
bel23.setAttribute("class", "form-group anexos")
var bel21 = document.createElement("label")
bel21.setAttribute("htmlFor", "anexos")
ac(bel21, ["Numero de Anexos"])
var bel22 = document.createElement("input")
bel22.setAttribute("type", "number")
bel22.setAttribute("id", "anexos")
bel22.setAttribute("name", "anexos")
bel22.setAttribute("required", "required")
bel22.setAttribute("class", "form-control")
ac(bel23, ["\n    ",bel21,"\n    ",bel22,"\n"])
var bel26 = document.createElement("div")
bel26.setAttribute("class", "form-group fRecepcion")
var bel24 = document.createElement("label")
bel24.setAttribute("htmlFor", "fRecepcion")
ac(bel24, ["Fecha de Recepcion"])
var bel25 = document.createElement("input")
bel25.setAttribute("type", "text")
bel25.setAttribute("id", "datepicker")
bel25.setAttribute("name", "fRecepcion")
bel25.setAttribute("required", "required")
bel25.setAttribute("class", "form-control")
ac(bel26, ["\n    ",bel24,"\n    ",bel25,"\n"])
var bel29 = document.createElement("div")
bel29.setAttribute("class", "form-group hRecepcion")
var bel27 = document.createElement("label")
bel27.setAttribute("htmlFor", "hRecepcion")
ac(bel27, ["Hora de Recepcion"])
var bel28 = document.createElement("input")
bel28.setAttribute("type", "time")
bel28.setAttribute("id", "hRecepcion")
bel28.setAttribute("name", "hRecepcion")
bel28.setAttribute("required", "required")
bel28.setAttribute("class", "form-control")
ac(bel29, ["\n    ",bel27,"\n    ",bel28,"\n"])
var bel32 = document.createElement("div")
bel32.setAttribute("class", "form-group send")
var bel30 = document.createElement("input")
bel30.setAttribute("type", "submit")
bel30.setAttribute("value", "Guardar")
bel30.setAttribute("class", "btn btn-primary btn-sm")
var bel31 = document.createElement("button")
bel31.setAttribute("id", "cancelar")
bel31.setAttribute("class", "btn btn-default btn-sm")
ac(bel31, ["Cancelar"])
ac(bel32, ["\n    ",bel30,"\n    ",bel31,"\n"])
ac(bel33, ["\n",bel2,"\n\n",bel5,"\n\n",bel11,"\n\n",bel14,"\n\n\n",bel17,"\n\n",bel20,"\n\n",bel23,"\n\n",bel26,"\n\n",bel29,"\n\n\n\n\n\n\n\n\n\n\n\n\n\n",bel32,"\n\n"])
      return bel33
    }());

}